### ISSUE TITLE
TypeError: unique() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by damienmarlier51** [KrishnaswamyLab/SAUCIE#1] opened 2017-12-21 10:01 UTC
updating numpy to 1.13.3 solved the issue

**Comment by antoinecomp** [comment] 2018-05-16 18:09
Hmm, maybe. Here is the output I have when checking numpy version for python and python 3 :

```
mike@mike-thinks:~/Programing/Rasa_tutorial/moodbot$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.version.version
'1.14.3'
>>> 
mike@mike-thinks:~/Programing/Rasa_tutorial/moodbot$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.version.version
'1.11.0'
```

**Comment by antoinecomp** [comment] 2018-05-23 17:13
Why did you close the issue ?if I run python3 I have :

```
(MoodbotEnv) mike@mike-thinks:~/Programing/Rasa/moodbot4$ python3 train_online.py 
Traceback (most recent call last):
  File "train_online.py", line 37, in <module>
    nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu/test')
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/interpreter.py", line 219, in __init__
    self._load_interpreter()
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/interpreter.py", line 238, in _load_interpreter
    os.environ))
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/model.py", line 230, in load
    skip_valdation)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/model.py", line 253, in create
    components.validate_requirements(model_metadata.pipeline)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/components.py", line 56, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/usr/local/lib/python3.5/dist-packages/rasa_nlu/registry.py", line 125, in get_component_class
    if component_name not in registered_components:
TypeError: unhashable type: 'dict'
```

**Comment by mattamodio** [comment] 2018-05-23 17:30
The issue has been reopened now that there is a comment awaiting a response, which there was not before.

I'm not sure what code is in the program train_online.py, since that is not a file in this repository. 
The top level line causing the problem is:
```
nlu_interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu/test')
```
Further following the traceback, the files where the error occurs are:
```
/usr/local/lib/python3.5/dist-packages/rasa_core/interpreter.py
/usr/local/lib/python3.5/dist-packages/rasa_nlu/components.py
/usr/local/lib/python3.5/dist-packages/rasa_nlu/registry.py
```
It looks like the original issue was indeed caused by not having the right version of numpy and this is now an issue with Rasa. Can you try removing Rasa? I have no knowledge of Rasa and cannot help with incorporating that tool.

**Comment by antoinecomp** [comment] 2018-05-23 20:30
My project relies is a chatbot which relies on Rasa, an open source machine learning toolkit for developers to expand bots beyond answering simple questions.
I just can't get rid of it

**Closed** 2018-10-16 03:49 UTC
